### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_fixed_uid' & ValueError: No radiological volume for {xy}

### ISSUE THREAD

**Issue by remogg** [raidionics/Raidionics#66] opened 2023-11-20 16:32 UTC
First off, thank you very much for providing this tool as an open-source solution. 
I am a radiologist and must admit that i have little programming knowledge regarding python. Thats why i am struggeling a bit trying to set this up. I already progressed getting the tool to run (didnt want to start segmenting in the beginning) but with this issue i dont seem to make any progress:

**Describe the bug**
When running the Reporting tool using direct DICOM import of T1, T2, FLAIR and T1-ce i get an error message (see below Nr 1)
When running it with compressed niftii (even the ones provided as test data) i get a different error message (see below Nr 2)

**Computer settings (please complete the following information):**
 - Operating System : Windows 10
 - CPU: Ryzen 5 3600
 - GPU: Nvidia RTX 2060

**Scanner-Data**
- Siemens Espree / Skyra 1.5T/3.0T
- Syngo MR BR19/  VB30C

**Error message 1**
20/11/2023 15.50 ; root ; INFO ; LOG: Pipeline - Registration from T1w (T0) to T1CE (T0) - Runtime: 43.97487211227417 seconds.
20/11/2023 15.50 ; root ; INFO ; LOG: Pipeline - Registration from T1w (T0) to T1CE (T0) - End (5/15)
20/11/2023 15.50 ; root ; INFO ; LOG: Pipeline - Apply registration from T1w (T0) to T1CE (T0) - Begin (6/15)
20/11/2023 15.50 ; root ; ERROR ; [RegistrationDeployerStep] Step setup failed with: Traceback (most recent call last):
  File "raidionicsrads\Pipelines\RegistrationDeployerStep.py", line 52, in setup
AttributeError: 'NoneType' object has no attribute '_fixed_uid'

**Error message 2**
20/11/2023 16.42 ; root ; ERROR ; [SegmentationStep] setup failed with: Traceback (most recent call last):
  File "raidionicsrads\Pipelines\SegmentationStep.py", line 71, in setup
ValueError: No radiological volume for {'timestamp': 0, 'sequence': 'T1-w', 'labels': None, 'space': {'timestamp': 0, 'sequence': 'T1-w'}}.

**my assumption**
I assume this is an issue with the DICOM headers but i wasnt really able to trace it down to what. 

Thank you very much.
LS

**Comment by andreped** [comment] 2023-11-20 22:15
Closed due to accidental duplicate of https://github.com/raidionics/Raidionics/issues/65.

**Closed by andreped** 2023-11-20 22:15 UTC
Labels: bug, duplicate
