### ISSUE TITLE
LGG reporting fails after T0 segmentation

### ISSUE THREAD

**Issue by slachtamarek** [raidionics/Raidionics#81] opened 2024-09-25 06:29 UTC
**Describe the bug**
When processing postop volumes in LGG there is a crash after preoperative segmentation. There is no problem in HGG. Did I miss something during processing?
Preop. image: FLAIR
Postop. images: T1w, T2w, FLAIR, T1ce

**Computer settings (please complete the following information):**
 - Operating System : macOS Sonoma 14.5 (MacMini)
 - Processor (CPU) type: M2 Apple silicon 8 GB RAM

**Error messages**
25/09/2024 08.17 ; root ; INFO ; LOG: Pipeline - Tumor segmentation in FLAIR (T0) - Runtime: 49.662046909332275 seconds.
25/09/2024 08.17 ; root ; INFO ; LOG: Pipeline - Tumor segmentation in FLAIR (T0) - End (2/6)
25/09/2024 08.17 ; root ; INFO ; LOG: Pipeline - Registration from FLAIR (T0) to MNI space - Begin (3/6)
25/09/2024 08.17 ; nibabel.global ; INFO ; pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
25/09/2024 08.17 ; nibabel.global ; INFO ; pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
25/09/2024 08.17 ; root ; INFO ; [RegistrationStep] Using cpp ANTs backend.
25/09/2024 08.17 ; root ; INFO ; [RegistrationStep] ANTs root located in /Applications/Raidionics.app/Contents/MacOS/utils/../ANTs.
25/09/2024 08.17 ; root ; ERROR ; [RegistrationStep] Registration failed with: Traceback (most recent call last):
  File "raidionicsrads/Pipelines/RegistrationStep.py", line 143, in __registration
  File "raidionicsrads/Utils/DataStructures/RegistrationStructure.py", line 31, in __init__
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/MacMini-MMM/radionics/patients/xxx/reporting/registration/1Warp.nii.gz'

Just segmentation error:

25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; Starting new HTTPS connection (1): github.com:443
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; https://github.com:443 "GET /raidionics/Raidionics-models/releases/download/1.2.0/raidionics_cloud_models_list_github.csv HTTP/1.1" 302 0
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; Starting new HTTPS connection (1): objects.githubusercontent.com:443
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; https://objects.githubusercontent.com:443 "GET /github-production-release-asset-2e65be/601122702/fe5a25c0-67a9-4910-a41c-ab75830fb390?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240925%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240925T065602Z&X-Amz-Expires=300&X-Amz-Signature=c634c342cb424101c13d41c2f2b9fa27681d47cab3bdd0fab36af8a47d4198c0&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Draidionics_cloud_models_list_github.csv&response-content-type=application%2Foctet-stream HTTP/1.1" 200 2660
25/09/2024 08.56 ; root ; ERROR ; No model exists with the provided name: MRI_LGGlioma_Postop.
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; Starting new HTTPS connection (1): github.com:443
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; https://github.com:443 "GET /raidionics/Raidionics-models/releases/download/1.2.0/raidionics_cloud_models_list_github.csv HTTP/1.1" 302 0
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; Starting new HTTPS connection (1): objects.githubusercontent.com:443
25/09/2024 08.56 ; urllib3.connectionpool ; DEBUG ; https://objects.githubusercontent.com:443 "GET /github-production-release-asset-2e65be/601122702/fe5a25c0-67a9-4910-a41c-ab75830fb390?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240925%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240925T065602Z&X-Amz-Expires=300&X-Amz-Signature=c634c342cb424101c13d41c2f2b9fa27681d47cab3bdd0fab36af8a47d4198c0&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Draidionics_cloud_models_list_github.csv&response-content-type=application%2Foctet-stream HTTP/1.1" 200 2660
25/09/2024 08.56 ; root ; ERROR ; No model exists with the provided name: MRI_LGGlioma_Postop.
25/09/2024 08.56 ; root ; ERROR ; Pipeline process for patient 69886, for task postop_segmentation_LGGlioma failed with: 
Traceback (most recent call last):
  File "utils/backend_logic.py", line 102, in run_pipeline
    pipeline = create_pipeline(model_name, patient_parameters, task)
  File "utils/logic/PipelineCreationHandler.py", line 71, in create_pipeline
    return __create_postop_segmentation_pipeline(model_name, patient_parameters)
  File "utils/logic/PipelineCreationHandler.py", line 187, in __create_postop_segmentation_pipeline
    infile = open(os.path.join(SoftwareConfigResources.getInstance().models_path, model_name, 'pipeline.json'), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mmm/.raidionics/resources/models/MRI_LGGlioma_Postop/pipeline.json'
25/09/2024 08.56 ; root ; INFO ; Saving patient results in: /Volumes/MacMini-MMM/radionics/patients/xxx

**Comment by dbouget** [comment] 2024-09-27 12:36
Hi @slachtamarek ,

This is actually not a bug (working on a better system for notifying the user in case of error/warning).
At the moment, only one model is available for postoperative reporting, and this is for glioblastomas. For the other three categories (i.e., low-grade gliomas, meningiomas, and metastases), no postoperative segmentation model is available, hence the postoperative reporting task will not succeed.

We are working on a postoperative package for low-grade gliomas which should be available in the months to come!

I'm closing this issue for now, and I will post a message when the model is available.

**Closed by dbouget** 2024-09-27 12:36 UTC
Labels: bug
